import pandas

pandas.set_option("display.unicode.east_asian_width", True)
data = pandas.read_csv("res1.csv")
data = data.dropna()
data = data.astype({"面积": "int64", "均价": "int64"})

data = data.sort_values(by="总价",ascending=False)
print("总价最贵:")
print(data.head(1))
print()
print("总价最便宜:")
print(data.tail(1))
print()
print("总价中位数:")
print(data["总价"].median())
print()

data = data.sort_values(by="均价",ascending=False)
print("均价最贵:")
print(data.head(1))
print()
print("均价最便宜:")
print(data.tail(1))
print()
print("均价中位数:")
print(data["均价"].median())
print()

std_lower_bound = data["总价"].mean() - 3 * data["总价"].std()
std_upper_bound = data["总价"].mean() + 3 * data["总价"].std()
data_clean_by_std = data.drop(data[(data["总价"] <= std_upper_bound) & (data["总价"] >= std_lower_bound)].index)
print("总价在均值三倍标准差以外的房屋:")
print(data_clean_by_std.head(4))
print()

q1 = data["均价"].quantile(0.25)
q3 = data["均价"].quantile(0.75)
box_lower_bound = q1 - 1.5 * (q3 - q1)
box_upper_bound = q3 + 1.5 * (q3 - q1)
data_clean_by_box = data.drop(data[(data["均价"] <= box_upper_bound) & (data["均价"] >= box_lower_bound)].index)
print("均价为异常值的房屋:")
print(data_clean_by_box.head(4))
print()

print("离散化:")
print(pandas.cut(data["均价"], [0, 100000, float("inf")]).value_counts())
